
import '@/styles/tailwind.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import clsx from 'clsx'

import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html 
			lang="en" 
			className={clsx(
        'h-full scroll-smooth bg-white antialiased',
        inter.variable,
      )}
		>
      <body className="flex h-full flex-col">
				<Header />
				<main>
					{children}
				</main>
				<Footer />
			</body>
    </html>
  )
}
